name: test

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - uses: actions/checkout@v3.0.2

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          # Useful for caching dependencies in monorepos
          cache-dependency-path: yarn.lock

      - name: Bootstrap
        run: |
          yarn bootstrap
          yarn build

      - name: Run tests
        run: |
          yarn test ci

      - name: Coveralls
        if: matrix.node-version == 18
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage/lcov.info
